"""
Generates sql/lookup_tables.sql — dimension tables that decode the numeric
IPEDS category codes (race, sex, award_level, etc.) used in enrollment.py
and completions.py into human-readable labels.

Source of truth: Urban Institute's own published variable metadata for the
Education Data Portal API (the same API pull_ipeds_data.py pulls from), not
hand-typed guesses. Pulled from:
    https://educationdata.urban.org/documentation/data/api-endpoint-varlist.json

That file lists every variable for every API endpoint, keyed by endpoint_id,
with a `values` field of "code":"label" pairs. The endpoint IDs used below
were identified by matching each endpoint's variable set against the columns
we actually load:
    endpoint 13 -> fall-enrollment/undergraduate/race/sex/
    endpoint 33 -> completions-cip-6/
    endpoint  1 -> directory/

Re-run this script any time the raw pull is redone, to keep the lookup
tables in sync with whatever Urban Institute's metadata says at pull time.
"""
import json
from datetime import datetime, timezone

import requests

VARLIST_URL = "https://educationdata.urban.org/documentation/data/api-endpoint-varlist.json"

# Codes observed in our actual pulled data that Urban Institute's own
# metadata does not document. Verified against api-endpoint-varlist.json
# on 2026-09-22 -- these codes are genuinely absent from every endpoint's
# "values" list, not a lookup mistake on our end. Rather than guess a
# label, we record what's known and flag it as unverified.
#   sex=4 in enrollment: 3,663 rows, all year=2022, no other year. Likely
#   an added gender-reporting category IPEDS introduced in later survey
#   cycles that Urban's published codebook hasn't caught up to -- but
#   that's a guess, not a confirmed source. Flag in the write-up.
MANUAL_OVERRIDES = {
    ("lookup_sex", 4): "UNDOCUMENTED (seen in 2022 enrollment data only; "
                        "not defined in Urban Institute's API metadata as "
                        "of 2026-09-22 -- verify before presenting)",
}

# (sql table name, endpoint_id, variable name in the varlist)
LOOKUPS = [
    ("lookup_race",            "13", "race"),
    ("lookup_sex",              "13", "sex"),
    ("lookup_ftpt",              "13", "ftpt"),
    ("lookup_level_of_study",    "13", "level_of_study"),
    ("lookup_degree_seeking",    "13", "degree_seeking"),
    ("lookup_class_level",       "13", "class_level"),
    ("lookup_award_level",       "33", "award_level"),
    ("lookup_majornum",          "33", "majornum"),
    ("lookup_sector",            "1",  "sector"),
    ("lookup_currently_active_ipeds", "1", "currently_active_ipeds"),
]


def parse_values(values_str):
    """The API returns values as a bare 'a":"b","c":"d"' string (no
    surrounding braces) -- wrap it so json can parse it, and keep codes
    as strings since some are negative sentinels (-1, -2, -3)."""
    return json.loads("{" + values_str + "}")


def sql_escape(s):
    return s.replace("'", "''")


def main():
    print(f"Fetching {VARLIST_URL} ...")
    resp = requests.get(VARLIST_URL, timeout=60)
    resp.raise_for_status()
    results = resp.json()["results"]

    by_key = {(r["endpoint_id"], r["variable"]): r for r in results}

    lines = [
        "-- Lookup / dimension tables decoding numeric IPEDS category codes",
        "-- into human-readable labels.",
        "--",
        f"-- Auto-generated by build_code_lookups.py on "
        f"{datetime.now(timezone.utc):%Y-%m-%d} from Urban Institute's own",
        f"-- API variable metadata ({VARLIST_URL}).",
        "-- Do not hand-edit -- rerun the script instead.",
        "",
    ]

    for table, endpoint_id, variable in LOOKUPS:
        row = by_key.get((endpoint_id, variable))
        if row is None:
            raise SystemExit(f"Could not find endpoint {endpoint_id} / {variable} in varlist")

        values = {int(k): v for k, v in parse_values(row["values"]).items()}
        for (override_table, override_code), override_label in MANUAL_OVERRIDES.items():
            if override_table == table:
                values[override_code] = override_label

        lines.append(f"DROP TABLE IF EXISTS {table};")
        lines.append(f"CREATE TABLE {table} (")
        lines.append("    code  integer PRIMARY KEY,")
        lines.append("    label text NOT NULL")
        lines.append(");")
        lines.append(f"INSERT INTO {table} (code, label) VALUES")
        value_lines = []
        for code, label in sorted(values.items()):
            value_lines.append(f"    ({code}, '{sql_escape(label)}')")
        lines.append(",\n".join(value_lines) + ";")
        lines.append("")

    out_path = "sql/lookup_tables.sql"
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out_path} ({len(LOOKUPS)} lookup tables)")


if __name__ == "__main__":
    main()
