"""
Builds ipeds_il_summary.xlsx -- the secondary/supplementary deliverable
described in the project scope. Pulls directly from the analysis views in
sql/analysis/ (run those against ipeds_il first), so this file is always
a snapshot of what's actually in the database, not a hand-maintained copy.
"""
import psycopg2
import pandas as pd
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.chart import LineChart, Reference
from openpyxl.utils import get_column_letter

DB_CONFIG = {"dbname": "ipeds_il", "user": "shanks", "host": "localhost", "port": 5432}
OUT_PATH = "ipeds_il_summary.xlsx"

HEADER_FILL = PatternFill(start_color="1F4E5F", end_color="1F4E5F", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True)

README_TEXT = [
    ("Illinois Public 2-Year College Enrollment & Completion Summary", True),
    ("", False),
    ("Source: Urban Institute Education Data Portal (educationdata.urban.org), "
     "wrapping raw IPEDS data. Scope: Illinois public 2-year (community) "
     "colleges, fips=17 sector=4. 63 institutions appear across the full "
     "1986-2024 span (colleges close, merge, or change unitid); 48 are "
     "active as of 2024. Years: 1986-2024 for enrollment/directory, "
     "1986-2023 for completions (2024 completions not yet published by "
     "IPEDS as of this pull).", False),
    ("", False),
    ("METHODOLOGY NOTES", True),
    ("- Enrollment and completions figures use only rows for years an "
     "institution was actually IPEDS-classified as Public, two-year -- "
     "the Urban Institute API doesn't support a sector filter on the "
     "enrollment/completions endpoints (confirmed against its own "
     "metadata), so this scoping is applied at the database layer instead.", False),
    ("- Enrollment totals use the pre-aggregated 'Total' marginal row for "
     "each year/institution, not a sum of every disaggregated row -- the "
     "raw data crosses full-time/part-time x degree-seeking x class level "
     "x sex x race, and summing all of it would overcount by roughly 1.5x.", False),
    ("- Completions totals count first majors only (COALESCE(majornum,1)=1). "
     "Second-major tracking only exists from 2000 onward; before that every "
     "row has a NULL majornum representing a student's only major. This "
     "avoids both under-counting pre-2000 data and double-counting "
     "double-major completers post-2000.", False),
    ("- Completions totals also exclude cipcode_6digit=99, which is a "
     "hidden 'Total across all CIP programs' marginal row (verified: it "
     "reconciles exactly against the sum of every real program code for "
     "the same institution/year). Summing across it alongside the real "
     "per-program rows would double every completions figure.", False),
    ("", False),
    ("KNOWN DATA CAVEATS", True),
    ("- 2010 IPEDS race/ethnicity category change (new federal OMB "
     "standards): pre-2010, Asian and Native Hawaiian/Pacific Islander "
     "were one combined category; post-2010 they split, and 'Two or more "
     "races' appeared with no pre-2010 equivalent. The 'Demographics "
     "(Comparable)' sheets merge these for a continuous 1986-2024 series; "
     "the 'Demographics (Raw)' sheets show the categories exactly as "
     "IPEDS reported them, discontinuity included.", False),
    ("- 2024 completions data is not yet published by IPEDS (confirmed via "
     "repeated, consistent errors specific to that year/dataset).", False),
    ("- One enrollment code is undocumented: sex=4 in 2022 data (3,663 "
     "rows) does not appear in Urban Institute's own published API "
     "metadata. Not included in the Sex breakdown sheets pending "
     "verification of what it represents.", False),
    ("- Program titles on the 'Completions by Program' sheet are sourced "
     "from NCES's own CIP code dictionaries across the 1985/1990/2000/2010 "
     "editions (the current 2020 edition file isn't fetchable without a "
     "JS-driven download, so 2020-2023 rows fall back to the 2010 title, "
     "correct for the large majority of codes). The 'cip_edition' column "
     "shows which edition supplied each title; not verified row-by-row "
     "for the rarer case of a code being reassigned to a different "
     "program across editions.", False),
    ("", False),
    ("Generated by build_excel_workbook.py from the ipeds_il Postgres "
     "database. Re-run after any data refresh to regenerate this file.", False),
]


def fetch_df(conn, view_name, order_by=None):
    query = f"SELECT * FROM {view_name}"
    if order_by:
        query += f" ORDER BY {order_by}"
    return pd.read_sql(query, conn)


def style_header(ws, ncols):
    for col in range(1, ncols + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center")
    ws.freeze_panes = "A2"


def autosize_columns(ws, df):
    for i, col in enumerate(df.columns, start=1):
        max_data_len = max((len(str(v)) for v in df[col].tolist()), default=0)
        width = max(len(str(col)), max_data_len) + 2
        ws.column_dimensions[get_column_letter(i)].width = min(width, 45)


def write_readme(writer):
    ws = writer.book.create_sheet("Read Me", 0)
    row = 1
    for text, is_header in README_TEXT:
        cell = ws.cell(row=row, column=1, value=text)
        if is_header:
            cell.font = Font(bold=True, size=13 if row == 1 else 12)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        ws.row_dimensions[row].height = 30 if text and not is_header else 18
        row += 1
    ws.column_dimensions["A"].width = 110


def write_sheet(writer, df, sheet_name):
    df.to_excel(writer, sheet_name=sheet_name, index=False)
    ws = writer.sheets[sheet_name]
    style_header(ws, len(df.columns))
    autosize_columns(ws, df)
    return ws


def add_line_chart(ws, df, title, y_cols, anchor="H2"):
    chart = LineChart()
    chart.title = title
    chart.style = 2
    chart.y_axis.title = "Count"
    chart.x_axis.title = "Year"
    n = len(df) + 1
    cats = Reference(ws, min_col=1, min_row=2, max_row=n)
    for col_idx in y_cols:
        data = Reference(ws, min_col=col_idx, min_row=1, max_row=n)
        chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.width, chart.height = 22, 11
    ws.add_chart(chart, anchor)


def main():
    conn = psycopg2.connect(**DB_CONFIG)

    sheets = {
        "Enrollment Trend (Statewide)": ("v_enrollment_trend_statewide", "year"),
        "Enrollment by Institution": ("v_enrollment_trend_by_institution", "inst_name, year"),
        "Enrollment by Class Level": ("v_enrollment_trend_class_level", "year, class_level"),
        "Enrollment Demog (Comparable)": ("v_enrollment_demographics_comparable", "year, race_group_comparable"),
        "Enrollment Demog (Raw)": ("v_enrollment_demographics_raw", "year, race, sex"),
        "Completions Trend (Statewide)": ("v_completions_trend_statewide", "year"),
        "Completions by Institution": ("v_completions_trend_by_institution", "inst_name, year"),
        "Completions by Award Level": ("v_completions_trend_by_award_level", "year, award_level"),
        "Completions by Program": ("v_completions_top_programs", "total_completions DESC"),
        "Completions Demog (Comparable)": ("v_completions_demographics_comparable", "year, race_group_comparable"),
        "Completions Demog (Raw)": ("v_completions_demographics_raw", "year, race, sex"),
    }

    dfs = {name: fetch_df(conn, view, order_by) for name, (view, order_by) in sheets.items()}
    conn.close()

    with pd.ExcelWriter(OUT_PATH, engine="openpyxl") as writer:
        write_readme(writer)
        for name, df in dfs.items():
            write_sheet(writer, df, name)

        enroll_ws = writer.sheets["Enrollment Trend (Statewide)"]
        add_line_chart(
            enroll_ws, dfs["Enrollment Trend (Statewide)"],
            "IL Public 2-Year College Enrollment, 1986-2024",
            y_cols=[2, 3, 4],
        )

        comp_ws = writer.sheets["Completions Trend (Statewide)"]
        add_line_chart(
            comp_ws, dfs["Completions Trend (Statewide)"],
            "IL Public 2-Year College Completions, 1986-2023",
            y_cols=[2],
        )

    print(f"Wrote {OUT_PATH} ({len(dfs)} data sheets + Read Me + 2 charts)")


if __name__ == "__main__":
    main()
