-- Lookup / dimension tables decoding numeric IPEDS category codes
-- into human-readable labels.
--
-- Auto-generated by build_code_lookups.py on 2026-09-22 from Urban Institute's own
-- API variable metadata (https://educationdata.urban.org/documentation/data/api-endpoint-varlist.json).
-- Do not hand-edit -- rerun the script instead.

DROP TABLE IF EXISTS lookup_race;
CREATE TABLE lookup_race (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_race (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'White'),
    (2, 'Black'),
    (3, 'Hispanic'),
    (4, 'Asian'),
    (5, 'American Indian or Alaska Native'),
    (6, 'Native Hawaiian or other Pacific Islander'),
    (7, 'Two or more races'),
    (8, 'Nonresident alien'),
    (9, 'Unknown'),
    (20, 'Other'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_sex;
CREATE TABLE lookup_sex (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_sex (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'Male'),
    (2, 'Female'),
    (3, 'Gender Not-Identified'),
    (4, 'UNDOCUMENTED (seen in 2022 enrollment data only; not defined in Urban Institute''s API metadata as of 2026-09-22 -- verify before presenting)'),
    (9, 'Unknown'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_ftpt;
CREATE TABLE lookup_ftpt (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_ftpt (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'Full-time'),
    (2, 'Part-time'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_level_of_study;
CREATE TABLE lookup_level_of_study (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_level_of_study (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'Undergraduate'),
    (2, 'Graduate'),
    (3, 'First professional'),
    (4, 'Postbaccalaureate'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_degree_seeking;
CREATE TABLE lookup_degree_seeking (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_degree_seeking (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (0, 'No'),
    (1, 'Yes'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_class_level;
CREATE TABLE lookup_class_level (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_class_level (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'First-time'),
    (2, 'Other (transfer-ins or non-first-time-entering)'),
    (3, 'Other (continuing)'),
    (4, 'Other (total)'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_award_level;
CREATE TABLE lookup_award_level (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_award_level (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (1, 'Award of less than one academic year'),
    (2, 'Award of less than two academic years'),
    (3, 'Award of at least one but less than two academic years'),
    (4, 'Associate''s degree'),
    (5, 'Award of at least one but less than four academic years'),
    (6, 'Award of at least two but less than four academic years'),
    (7, 'Bachelor''s degree'),
    (8, 'Postbaccalaureate or post-master''s certificate'),
    (9, 'Master''s degree'),
    (20, 'Doctor''s degree (until 2008)'),
    (21, 'First-professional degree (until 2008)'),
    (22, 'Doctor''s degree, research/scholarship (starting 2007)'),
    (23, 'Doctor''s degree, professional practice (starting 2007)'),
    (24, 'Doctor''s degree, other (starting 2007)'),
    (30, 'Certificate of less than 12 weeks'),
    (31, 'Certificates of at least 12 weeks but less than 1 year'),
    (32, 'Certificate of at least 1 year but less than 2 years'),
    (33, 'Certificate of at least 2 years but less than 4 years'),
    (99, 'Total');

DROP TABLE IF EXISTS lookup_majornum;
CREATE TABLE lookup_majornum (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_majornum (code, label) VALUES
    (1, 'First major'),
    (2, 'Second major');

DROP TABLE IF EXISTS lookup_sector;
CREATE TABLE lookup_sector (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_sector (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Sector unknown (not active)'),
    (0, 'Administrative unit'),
    (1, 'Public, four-year or above'),
    (2, 'Private not-for-profit, four-year or above'),
    (3, 'Private for-profit, four-year or above'),
    (4, 'Public, two-year'),
    (5, 'Private not-for-profit, two-year'),
    (6, 'Private for-profit, two-year'),
    (7, 'Public, less-than two-year'),
    (8, 'Private not-for-profit, less-than-two-year'),
    (9, 'Private for-profit, less-than-two-year');

DROP TABLE IF EXISTS lookup_currently_active_ipeds;
CREATE TABLE lookup_currently_active_ipeds (
    code  integer PRIMARY KEY,
    label text NOT NULL
);
INSERT INTO lookup_currently_active_ipeds (code, label) VALUES
    (-3, 'Suppressed data'),
    (-2, 'Not applicable'),
    (-1, 'Missing/not reported'),
    (0, 'No'),
    (1, 'Yes');

